## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns = ["EIN", "SPECIAL_CONSIDERATIONS"])

application_df.head()

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,142590,1

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

NAME                19568
APPLICATION_TYPE       17
AFFILIATION             6
CLASSIFICATION         71
USE_CASE                5
ORGANIZATION            4
STATUS                  2
INCOME_AMT              9
ASK_AMT              8747
IS_SUCCESSFUL           2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
application_counts = application_df["APPLICATION_TYPE"].value_counts()

application_counts

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = application_counts.iloc[8:].index
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
classification_counts = application_df["CLASSIFICATION"].value_counts()

classification_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
new_classification_counts = classification_counts.loc[classification_counts > 1]

new_classification_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE
classifications_to_replace = classification_counts.iloc[5:].index
# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [9]:
#bin by names
name_counts = application_df["NAME"].value_counts()

name_counts

NAME
PARENT BOOSTER USA INC                                                  1260
TOPS CLUB INC                                                            765
UNITED STATES BOWLING CONGRESS INC                                       700
WASHINGTON STATE UNIVERSITY                                              492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                          408
                                                                        ...
ST LOUIS SLAM WOMENS FOOTBALL                                              1
AIESEC ALUMNI IBEROAMERICA CORP                                            1
WEALLBLEEDRED ORG INC                                                      1
AMERICAN SOCIETY FOR STANDARDS IN MEDIUMSHIP & PSYCHICAL INVESTIGATI       1
WATERHOUSE CHARITABLE TR                                                   1
Name: count, Length: 19568, dtype: int64

In [10]:
higher_name_counts = name_counts.loc[name_counts>200]
higher_name_counts

NAME
PARENT BOOSTER USA INC                                                1260
TOPS CLUB INC                                                          765
UNITED STATES BOWLING CONGRESS INC                                     700
WASHINGTON STATE UNIVERSITY                                            492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                        408
PTA TEXAS CONGRESS                                                     368
SOROPTIMIST INTERNATIONAL OF THE AMERICAS INC                          331
ALPHA PHI SIGMA                                                        313
TOASTMASTERS INTERNATIONAL                                             293
MOST WORSHIPFUL STRINGER FREE AND ACCEPTED MASONS                      287
LITTLE LEAGUE BASEBALL INC                                             277
INTERNATIONAL ASSOCIATION OF LIONS CLUBS                               266
MOMS CLUB                                                              210
INTERNATIONAL ASSOCIATION OF SHEET METAL AIR RAIL & TRANSPORTATION     206
Name: count, dtype: int64

In [11]:
names_to_replace = name_counts.iloc[14:].index

for names in names_to_replace:
    application_df['NAME'] = application_df['NAME'].replace(names,"Other")
    
# Check to make sure binning was successful
application_df['NAME'].value_counts()

NAME
Other                                                                 28123
PARENT BOOSTER USA INC                                                 1260
TOPS CLUB INC                                                           765
UNITED STATES BOWLING CONGRESS INC                                      700
WASHINGTON STATE UNIVERSITY                                             492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                         408
PTA TEXAS CONGRESS                                                      368
SOROPTIMIST INTERNATIONAL OF THE AMERICAS INC                           331
ALPHA PHI SIGMA                                                         313
TOASTMASTERS INTERNATIONAL                                              293
MOST WORSHIPFUL STRINGER FREE AND ACCEPTED MASONS                       287
LITTLE LEAGUE BASEBALL INC                                              277
INTERNATIONAL ASSOCIATION OF LIONS CLUBS                                266
MOMS CLUB                                                               210
INTERNATIONAL ASSOCIATION OF SHEET METAL AIR RAIL & TRANSPORTATION      206
Name: count, dtype: int64

In [12]:
application_df.dtypes

NAME                object
APPLICATION_TYPE    object
AFFILIATION         object
CLASSIFICATION      object
USE_CASE            object
ORGANIZATION        object
STATUS               int64
INCOME_AMT          object
ASK_AMT              int64
IS_SUCCESSFUL        int64
dtype: object

In [13]:
# Convert categorical data to numeric with `pd.get_dummies`
numeric_dummies = pd.get_dummies(application_df).astype("int64")

numeric_dummies.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_ALPHA PHI SIGMA,NAME_AMATEUR ATHLETIC UNION OF THE UNITED STATES INC,NAME_INTERNATIONAL ASSOCIATION OF LIONS CLUBS,NAME_INTERNATIONAL ASSOCIATION OF SHEET METAL AIR RAIL & TRANSPORTATION,NAME_LITTLE LEAGUE BASEBALL INC,NAME_MOMS CLUB,NAME_MOST WORSHIPFUL STRINGER FREE AND ACCEPTED MASONS,...,ORGANIZATION_Trust,INCOME_AMT_0,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M
0,1,5000,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,1,108590,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,1,5000,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,1,6692,1,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
4,1,142590,1,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0

In [14]:
# Split our preprocessed data into our features and target arrays
X = numeric_dummies.drop(["IS_SUCCESSFUL"], axis = 1)
y = numeric_dummies["IS_SUCCESSFUL"]
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 78)

In [15]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)

X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [29]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units = 8, activation = "tanh", input_dim = len(X_train_scaled[0])))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units = 16, activation = "tanh"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units = 32, activation = "tanh"))

# Output layer
nn.add(tf.keras.layers.Dense(units = 1, activation = "sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_12 (Dense)                │ (None, 8)              │           456 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 16)             │           144 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 32)             │           544 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_15 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,177 (4.60 KB)

 Trainable params: 1,177 (4.60 KB)

 Non-trainable params: 0 (0.00 B)

In [30]:
# Compile the model
nn.compile(loss = "binary_crossentropy", optimizer = "adam", metrics = ["accuracy"])

In [33]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs = 100)

Epoch 1/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 1s 765us/step - accuracy: 0.7591 - loss: 0.4972 - val_accuracy: 0.7505 - val_loss: 0.4974
Epoch 2/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 668us/step - accuracy: 0.7712 - loss: 0.4826 - val_accuracy: 0.7489 - val_loss: 0.5009
Epoch 3/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 654us/step - accuracy: 0.7585 - loss: 0.4929 - val_accuracy: 0.7484 - val_loss: 0.5006
Epoch 4/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 646us/step - accuracy: 0.7578 - loss: 0.4971 - val_accuracy: 0.7492 - val_loss: 0.5002
Epoch 5/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 662us/step - accuracy: 0.7619 - loss: 0.4955 - val_accuracy: 0.7512 - val_loss: 0.4994
Epoch 6/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 647us/step - accuracy: 0.7640 - loss: 0.4904 - val_accuracy: 0.7515 - val_loss: 0.4990
Epoch 7/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 653us/step - accuracy: 0.7623 - loss: 0.4896 - val_accuracy: 0.7520 - val_loss: 0.4990
Epoch 8/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 653us/step - accuracy: 0.7651 - loss: 0.4888 - val_accuracy: 0.7505 - val_loss: 0.4997
Epoch 9/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 672us/step - accuracy: 0.7599 - loss: 0.4947 - val_accuracy: 0.7471 - val_loss: 0.5015
Epoch 10/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 663us/step - accuracy: 0.7626 - loss: 0.4925 - val_accuracy: 0.7512 - val_loss: 0.4999
Epoch 11/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 654us/step - accuracy: 0.7655 - loss: 0.4858 - val_accuracy: 0.7492 - val_loss: 0.5008
Epoch 12/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 665us/step - accuracy: 0.7625 - loss: 0.4908 - val_accuracy: 0.7489 - val_loss: 0.5016
Epoch 13/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 672us/step - accuracy: 0.7639 - loss: 0.4889 - val_accuracy: 0.7492 - val_loss: 0.5017
Epoch 14/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 1s 750us/step - accuracy: 0.7670 - loss: 0.4851 - val_accuracy: 0.7520 - val_loss: 0.4999
Epoch 15/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 656us/step - accuracy: 0.7579 - loss: 0.4974 - val_accuracy: 0.7520 - val_loss: 0.5006
Epoch 16/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 687us/step - accuracy: 0.7543 - loss: 0.4960 - val_accuracy: 0.7499 - val_loss: 0.5020
Epoch 17/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 683us/step - accuracy: 0.7601 - loss: 0.4964 - val_accuracy: 0.7492 - val_loss: 0.5012
Epoch 18/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 662us/step - accuracy: 0.7589 - loss: 0.4949 - val_accuracy: 0.7489 - val_loss: 0.5025
Epoch 19/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 660us/step - accuracy: 0.7643 - loss: 0.4904 - val_accuracy: 0.7489 - val_loss: 0.5020
Epoch 20/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 654us/step - accuracy: 0.7612 - loss: 0.4908 - val_accuracy: 0.7492 - val_loss: 0.5018
Epoch 21/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 666us/step - accuracy: 0.7632 - loss: 0.4891 - val_accuracy: 0.7484 - val_loss: 0.5006
Epoch 22/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 672us/step - accuracy: 0.7638 - loss: 0.4900 - val_accuracy: 0.7468 - val_loss: 0.5031
Epoch 23/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 1s 780us/step - accuracy: 0.7606 - loss: 0.4936 - val_accuracy: 0.7489 - val_loss: 0.5017
Epoch 24/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 704us/step - accuracy: 0.7656 - loss: 0.4903 - val_accuracy: 0.7510 - val_loss: 0.5012
Epoch 25/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 678us/step - accuracy: 0.7620 - loss: 0.4915 - val_accuracy: 0.7486 - val_loss: 0.5028
Epoch 26/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 1s 719us/step - accuracy: 0.7651 - loss: 0.4862 - val_accuracy: 0.7486 - val_loss: 0.5020
Epoch 27/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 688us/step - accuracy: 0.7637 - loss: 0.4894 - val_accuracy: 0.7484 - val_loss: 0.5032
Epoch 28/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 649us/step - accuracy: 0.7615 - loss: 0.4894 - val_accuracy: 0.7494 - val_loss: 0.5037
Epoch 29/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 666us/step - accuracy: 0.7604 - loss: 0.4981 - val_accuracy: 0.7486 - val_loss: 0.5013
Epoch 30/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 647us/step - accuracy: 0.7595 - loss: 0.4951 - val_accuracy: 0.7486 - val_loss: 0.5026
Epoch 31/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 654us/step - accuracy: 0.7621 - loss: 0.4950 - val_accuracy: 0.7489 - val_loss: 0.5027
Epoch 32/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 641us/step - accuracy: 0.7603 - loss: 0.4940 - val_accuracy: 0.7481 - val_loss: 0.5020
Epoch 33/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 640us/step - accuracy: 0.7602 - loss: 0.4957 - val_accuracy: 0.7466 - val_loss: 0.5036
Epoch 34/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 662us/step - accuracy: 0.7644 - loss: 0.4918 - val_accuracy: 0.7484 - val_loss: 0.5032
Epoch 35/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 1s 645us/step - accuracy: 0.7595 - loss: 0.4954 - val_accuracy: 0.7492 - val_loss: 0.5029
Epoch 36/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 683us/step - accuracy: 0.7652 - loss: 0.4909 - val_accuracy: 0.7471 - val_loss: 0.5029
Epoch 37/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 665us/step - accuracy: 0.7609 - loss: 0.4927 - val_accuracy: 0.7463 - val_loss: 0.5032
Epoch 38/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 672us/step - accuracy: 0.7645 - loss: 0.4873 - val_accuracy: 0.7466 - val_loss: 0.5040
Epoch 39/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 662us/step - accuracy: 0.7562 - loss: 0.4945 - val_accuracy: 0.7481 - val_loss: 0.5062
Epoch 40/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 656us/step - accuracy: 0.7653 - loss: 0.4895 - val_accuracy: 0.7466 - val_loss: 0.5038
Epoch 41/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 1s 719us/step - accuracy: 0.7618 - loss: 0.4913 - val_accuracy: 0.7476 - val_loss: 0.5045
Epoch 42/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 690us/step - accuracy: 0.7592 - loss: 0.4960 - val_accuracy: 0.7494 - val_loss: 0.5035
Epoch 43/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 679us/step - accuracy: 0.7610 - loss: 0.4946 - val_accuracy: 0.7505 - val_loss: 0.5032
Epoch 44/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 685us/step - accuracy: 0.7648 - loss: 0.4902 - val_accuracy: 0.7479 - val_loss: 0.5033
Epoch 45/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 675us/step - accuracy: 0.7654 - loss: 0.4900 - val_accuracy: 0.7484 - val_loss: 0.5022
Epoch 46/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 1s 709us/step - accuracy: 0.7632 - loss: 0.4918 - val_accuracy: 0.7476 - val_loss: 0.5060
Epoch 47/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 651us/step - accuracy: 0.7629 - loss: 0.4896 - val_accuracy: 0.7479 - val_loss: 0.5030
Epoch 48/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 650us/step - accuracy: 0.7652 - loss: 0.4877 - val_accuracy: 0.7481 - val_loss: 0.5028
Epoch 49/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 653us/step - accuracy: 0.7580 - loss: 0.4931 - val_accuracy: 0.7468 - val_loss: 0.5033
Epoch 50/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 669us/step - accuracy: 0.7617 - loss: 0.4923 - val_accuracy: 0.7484 - val_loss: 0.5031
Epoch 51/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 699us/step - accuracy: 0.7628 - loss: 0.4914 - val_accuracy: 0.7468 - val_loss: 0.5056
Epoch 52/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 665us/step - accuracy: 0.7664 - loss: 0.4862 - val_accuracy: 0.7505 - val_loss: 0.5026
Epoch 53/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 1s 711us/step - accuracy: 0.7553 - loss: 0.4987 - val_accuracy: 0.7473 - val_loss: 0.5044
Epoch 54/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 654us/step - accuracy: 0.7673 - loss: 0.4836 - val_accuracy: 0.7476 - val_loss: 0.5044
Epoch 55/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 682us/step - accuracy: 0.7606 - loss: 0.4951 - val_accuracy: 0.7497 - val_loss: 0.5039
Epoch 56/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 1s 738us/step - accuracy: 0.7630 - loss: 0.4894 - val_accuracy: 0.7489 - val_loss: 0.5042
Epoch 57/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 683us/step - accuracy: 0.7611 - loss: 0.4912 - val_accuracy: 0.7468 - val_loss: 0.5050
Epoch 58/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 649us/step - accuracy: 0.7618 - loss: 0.4898 - val_accuracy: 0.7502 - val_loss: 0.5040
Epoch 59/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 659us/step - accuracy: 0.7603 - loss: 0.4974 - val_accuracy: 0.7492 - val_loss: 0.5037
Epoch 60/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 668us/step - accuracy: 0.7637 - loss: 0.4885 - val_accuracy: 0.7499 - val_loss: 0.5034
Epoch 61/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 1s 720us/step - accuracy: 0.7614 - loss: 0.4903 - val_accuracy: 0.7481 - val_loss: 0.5041
Epoch 62/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 682us/step - accuracy: 0.7619 - loss: 0.4929 - val_accuracy: 0.7489 - val_loss: 0.5046
Epoch 63/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 663us/step - accuracy: 0.7585 - loss: 0.4970 - val_accuracy: 0.7479 - val_loss: 0.5056
Epoch 64/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 677us/step - accuracy: 0.7614 - loss: 0.4945 - val_accuracy: 0.7494 - val_loss: 0.5051
Epoch 65/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 654us/step - accuracy: 0.7628 - loss: 0.4905 - val_accuracy: 0.7494 - val_loss: 0.5049
Epoch 66/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 691us/step - accuracy: 0.7604 - loss: 0.4950 - val_accuracy: 0.7489 - val_loss: 0.5044
Epoch 67/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 673us/step - accuracy: 0.7600 - loss: 0.4922 - val_accuracy: 0.7502 - val_loss: 0.5049
Epoch 68/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 657us/step - accuracy: 0.7659 - loss: 0.4877 - val_accuracy: 0.7460 - val_loss: 0.5072
Epoch 69/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 665us/step - accuracy: 0.7660 - loss: 0.4889 - val_accuracy: 0.7484 - val_loss: 0.5044
Epoch 70/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 675us/step - accuracy: 0.7622 - loss: 0.4892 - val_accuracy: 0.7476 - val_loss: 0.5060
Epoch 71/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 665us/step - accuracy: 0.7598 - loss: 0.4944 - val_accuracy: 0.7468 - val_loss: 0.5047
Epoch 72/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 678us/step - accuracy: 0.7564 - loss: 0.4951 - val_accuracy: 0.7455 - val_loss: 0.5076
Epoch 73/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 684us/step - accuracy: 0.7564 - loss: 0.4967 - val_accuracy: 0.7492 - val_loss: 0.5049
Epoch 74/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 678us/step - accuracy: 0.7647 - loss: 0.4894 - val_accuracy: 0.7466 - val_loss: 0.5052
Epoch 75/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 703us/step - accuracy: 0.7597 - loss: 0.4915 - val_accuracy: 0.7471 - val_loss: 0.5056
Epoch 76/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 644us/step - accuracy: 0.7555 - loss: 0.4954 - val_accuracy: 0.7471 - val_loss: 0.5043
Epoch 77/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 667us/step - accuracy: 0.7578 - loss: 0.4972 - val_accuracy: 0.7460 - val_loss: 0.5056
Epoch 78/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 687us/step - accuracy: 0.7650 - loss: 0.4895 - val_accuracy: 0.7489 - val_loss: 0.5050
Epoch 79/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 663us/step - accuracy: 0.7582 - loss: 0.5001 - val_accuracy: 0.7463 - val_loss: 0.5094
Epoch 80/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 708us/step - accuracy: 0.7598 - loss: 0.4939 - val_accuracy: 0.7479 - val_loss: 0.5045
Epoch 81/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 1s 716us/step - accuracy: 0.7612 - loss: 0.4907 - val_accuracy: 0.7512 - val_loss: 0.5045
Epoch 82/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 654us/step - accuracy: 0.7605 - loss: 0.4919 - val_accuracy: 0.7486 - val_loss: 0.5046
Epoch 83/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 1s 739us/step - accuracy: 0.7635 - loss: 0.4885 - val_accuracy: 0.7497 - val_loss: 0.5049
Epoch 84/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 678us/step - accuracy: 0.7633 - loss: 0.4882 - val_accuracy: 0.7471 - val_loss: 0.5060
Epoch 85/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 657us/step - accuracy: 0.7633 - loss: 0.4907 - val_accuracy: 0.7458 - val_loss: 0.5097
Epoch 86/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 659us/step - accuracy: 0.7628 - loss: 0.4918 - val_accuracy: 0.7489 - val_loss: 0.5041
Epoch 87/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 645us/step - accuracy: 0.7637 - loss: 0.4922 - val_accuracy: 0.7453 - val_loss: 0.5077
Epoch 88/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 671us/step - accuracy: 0.7629 - loss: 0.4909 - val_accuracy: 0.7463 - val_loss: 0.5062
Epoch 89/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 652us/step - accuracy: 0.7614 - loss: 0.4948 - val_accuracy: 0.7460 - val_loss: 0.5068
Epoch 90/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 649us/step - accuracy: 0.7591 - loss: 0.4918 - val_accuracy: 0.7473 - val_loss: 0.5048
Epoch 91/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 1s 671us/step - accuracy: 0.7621 - loss: 0.4894 - val_accuracy: 0.7435 - val_loss: 0.5051
Epoch 92/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 653us/step - accuracy: 0.7578 - loss: 0.4917 - val_accuracy: 0.7460 - val_loss: 0.5069
Epoch 93/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 660us/step - accuracy: 0.7616 - loss: 0.4909 - val_accuracy: 0.7479 - val_loss: 0.5046
Epoch 94/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 670us/step - accuracy: 0.7578 - loss: 0.4975 - val_accuracy: 0.7489 - val_loss: 0.5042
Epoch 95/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 646us/step - accuracy: 0.7629 - loss: 0.4888 - val_accuracy: 0.7473 - val_loss: 0.5051
Epoch 96/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 706us/step - accuracy: 0.7608 - loss: 0.4905 - val_accuracy: 0.7466 - val_loss: 0.5052
Epoch 97/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 679us/step - accuracy: 0.7615 - loss: 0.4884 - val_accuracy: 0.7476 - val_loss: 0.5050
Epoch 98/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 669us/step - accuracy: 0.7699 - loss: 0.4814 - val_accuracy: 0.7479 - val_loss: 0.5060
Epoch 99/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 1s 731us/step - accuracy: 0.7617 - loss: 0.4920 - val_accuracy: 0.7479 - val_loss: 0.5054
Epoch 100/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 0s 672us/step - accuracy: 0.7588 - loss: 0.4953 - val_accuracy: 0.7448 - val_loss: 0.5059

In [34]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)

print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - 439us/step - accuracy: 0.7478 - loss: 0.5081
Loss: 0.5081209540367126, Accuracy: 0.7477551102638245

In [20]:
# Export our model to HDF5 file
#nn.save("Models/AlphabetSoupCharityOptimized.h5")